export const events = [
  {
    title: "Google I/O 2026",
    image: "/images/event1.png",
    slug: "google-io-2026",
    location: "Mountain View, CA, USA",
    date: "May 20, 2026",
    time: "10:00 AM PDT",
  },
  {
    title: "Microsoft Build 2026",
    image: "/images/event2.png",
    slug: "microsoft-build-2026",
    location: "Seattle, WA, USA",
    date: "May 27, 2026",
    time: "9:00 AM PDT",
  },
  {
    title: "KubeCon + CloudNativeCon Europe 2026",
    image: "/images/event3.png",
    slug: "kubecon-europe-2026",
    location: "Amsterdam, Netherlands",
    date: "April 14, 2026",
    time: "9:30 AM CET",
  },
  {
    title: "ETHGlobal Hackathon Bengaluru 2026",
    image: "/images/event4.png",
    slug: "ethglobal-bengaluru-2026",
    location: "Bengaluru, India",
    date: "June 12, 2026",
    time: "6:00 PM IST",
  },
  {
    title: "JSNation Conference 2026",
    image: "/images/event5.png",
    slug: "jsnation-2026",
    location: "Amsterdam, Netherlands",
    date: "June 18, 2026",
    time: "10:00 AM CET",
  },
  {
    title: "PyCon US 2026",
    image: "/images/event6.png",
    slug: "pycon-us-2026",
    location: "Pittsburgh, PA, USA",
    date: "April 22, 2026",
    time: "9:00 AM EDT",
  },
];